In [97]:
from numpy import random
import numpy as np # importando numpy
from scipy import stats # importando scipy.stats
import pandas as pd # importando pandas


# ejercicio 1 

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [98]:
def dimension(arr):
    x= (arr.shape) 
    y=len(x)
    if y>1:
        print ("Error")
    else: 
        dff=pd.DataFrame(arr)
        print (dff.describe())
        print ("la varianza es ", dff.var()) 
        print ("la suma es ", dff.sum()) 
    

In [102]:
arr=random.randint(100, size=(5,5))

In [103]:
dimension(arr)

Error


# ejercicio 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [104]:
def cuadricula (N):
    a = random.randint(100, size=(N, N))
    return a

In [105]:
cuadricula (10)

array([[42, 31, 37, 87, 14, 45, 21, 82, 18, 97],
       [85, 29, 70, 33, 68, 28, 41, 13, 52, 24],
       [43, 64, 29, 87, 24, 30, 23, 13, 77, 43],
       [23, 15, 15, 30, 65, 10, 39, 38, 73, 46],
       [91, 27, 31, 82, 55, 41, 32,  9, 16, 41],
       [28, 44, 63, 35, 43, 52, 67, 34,  8, 80],
       [99, 40, 20, 61, 81, 24, 97, 74, 20, 50],
       [96, 79, 74, 40, 79, 84, 88, 68, 54, 36],
       [27, 49, 37, 69, 25, 46, 63, 92, 76, 74],
       [18, 80, 98, 47, 57,  0, 10, 83, 77, 80]])

# ejercicio 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [65]:
def tabla (N,M):
    t = random.randint(100, size=(N, M))
    fila=t.sum(axis=1) #cada fila
    columna=t.sum(axis=0) # cada columna
    return (t,"los totales de las filas son , ", fila, "y los totales de las columnas son ", columna)

In [66]:
tabla (10,5)

(array([[86,  2, 33, 40, 45],
        [66, 20, 51, 58, 74],
        [44, 54,  5, 51, 15],
        [67, 87,  5, 59, 20],
        [57, 31,  1,  2, 58],
        [81, 12, 68, 33, 92],
        [30, 51, 70, 99, 33],
        [93, 48, 62, 96, 96],
        [33, 85, 99, 85,  0],
        [52,  5, 72, 97, 34]]),
 'los totales de las filas son , ',
 array([206, 269, 169, 238, 149, 286, 283, 395, 302, 260]),
 'y los totales de las columnas son ',
 array([609, 395, 466, 620, 467]))

# ejercicio 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [93]:
t = random.randint(100, size=(3,3))
t

array([[30, 74, 37],
       [52, 56, 36],
       [85, 23, 67]])

In [94]:
np.corrcoef(t)

array([[ 1.        ,  0.5355375 , -0.99056519],
       [ 0.5355375 ,  1.        , -0.41475095],
       [-0.99056519, -0.41475095,  1.        ]])

devuelve la covarianza normalizada. a=1er array b= 2d c= 3r. Matriz te muestra  a,a - a,b - a,c / b,a - b,b - b,c / c,a - c,b - c,c.  covarianza es un valor que indica el grado de variación conjunta de dos variables aleatorias respecto a sus medias.