In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
columnas=["id", "titulo", "genero"]

In [19]:
base = pd.read_table(r"C:\\DataScience\\string4\\PRE-PROCESSING-DATA-main\\movies.dat",sep ="::", encoding = "ISO-8859-1", engine='python', header = None, names = columnas, index_col="id" )
base.head()

titulo                        genero
id                                                                  
1                     Toy Story (1995)   Animation|Children's|Comedy
2                       Jumanji (1995)  Adventure|Children's|Fantasy
3              Grumpier Old Men (1995)                Comedy|Romance
4             Waiting to Exhale (1995)                  Comedy|Drama
5   Father of the Bride Part II (1995)                        Comedy

In [18]:
base.shape

(3883, 2)

In [23]:
base.describe()

titulo genero
count               3883   3883
unique              3883    301
top     Toy Story (1995)  Drama
freq                   1    843

In [25]:
base["genero"]

id
1        Animation|Children's|Comedy
2       Adventure|Children's|Fantasy
3                     Comedy|Romance
4                       Comedy|Drama
5                             Comedy
                    ...             
3948                          Comedy
3949                           Drama
3950                           Drama
3951                           Drama
3952                  Drama|Thriller
Name: genero, Length: 3883, dtype: object

In [20]:
Generos= []

In [27]:
for i in base["genero"]:
    Generos.extend(i.split("|"))

In [28]:
Generos

['Animation',
 "Children's",
 'Comedy',
 'Adventure',
 "Children's",
 'Fantasy',
 'Comedy',
 'Romance',
 'Comedy',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Thriller',
 'Comedy',
 'Romance',
 'Adventure',
 "Children's",
 'Action',
 'Action',
 'Adventure',
 'Thriller',
 'Comedy',
 'Drama',
 'Romance',
 'Comedy',
 'Horror',
 'Animation',
 "Children's",
 'Drama',
 'Action',
 'Adventure',
 'Romance',
 'Drama',
 'Thriller',
 'Drama',
 'Romance',
 'Thriller',
 'Comedy',
 'Action',
 'Action',
 'Comedy',
 'Drama',
 'Crime',
 'Drama',
 'Thriller',
 'Thriller',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Romance',
 'Drama',
 'Drama',
 'Romance',
 'Adventure',
 'Sci-Fi',
 'Drama',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Adventure',
 'Romance',
 "Children's",
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Drama',
 'Documentary',
 'Comedy',
 'Comedy',
 'Romance',
 'Drama',
 'Drama',
 'War',
 'Action',
 'Crime',
 'Drama',
 'Drama',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Drama',
 'Romance',
 'Crime',
 'Thrill

In [31]:
Cat_genero=pd.unique(Generos)

In [33]:
Cat_genero

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [46]:
Y=base["titulo"]

In [52]:
year=Y[1:5]

In [53]:
year

id
2                        Jumanji (1995)
3               Grumpier Old Men (1995)
4              Waiting to Exhale (1995)
5    Father of the Bride Part II (1995)
Name: titulo, dtype: object

In [57]:
base.titulo.str.slice(-6)

id
1       (1995)
2       (1995)
3       (1995)
4       (1995)
5       (1995)
         ...  
3948    (2000)
3949    (2000)
3950    (2000)
3951    (2000)
3952    (2000)
Name: titulo, Length: 3883, dtype: object

In [63]:
base["Nom_pelicula"]=base.titulo.str.slice(stop=-6)

In [60]:
base["year"]=base.titulo.str.findall(r"\d{4}").str.get(0)

In [65]:
base=base.drop("titulo", axis=1)

In [66]:
base

genero  year                  Nom_pelicula
id                                                                    
1      Animation|Children's|Comedy  1995                    Toy Story 
2     Adventure|Children's|Fantasy  1995                      Jumanji 
3                   Comedy|Romance  1995             Grumpier Old Men 
4                     Comedy|Drama  1995            Waiting to Exhale 
5                           Comedy  1995  Father of the Bride Part II 
...                            ...   ...                           ...
3948                        Comedy  2000             Meet the Parents 
3949                         Drama  2000          Requiem for a Dream 
3950                         Drama  2000                    Tigerland 
3951                         Drama  2000             Two Family House 
3952                Drama|Thriller  2000               Contender, The 

[3883 rows x 3 columns]

In [67]:
base["genero"].value_counts()

Drama                                  843
Comedy                                 521
Horror                                 178
Comedy|Drama                           162
Comedy|Romance                         142
                                      ... 
Action|Comedy|Crime|Horror|Thriller      1
Action|Drama|Thriller|War                1
Action|Adventure|Children's              1
Action|Adventure|Children's|Fantasy      1
Adventure|Crime|Sci-Fi|Thriller          1
Name: genero, Length: 301, dtype: int64

In [68]:
len(base)

3883

In [73]:
len(Cat_genero)

18

In [72]:
cero_matriz = np.zeros((len(base), len(Cat_genero)))
cero_matriz.shape

(3883, 18)

In [74]:
cero_matriz

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [75]:
sum(cero_matriz)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [76]:
len(sum(cero_matriz))

18

In [77]:
dummies = pd.DataFrame(cero_matriz, columns = Cat_genero)
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
1        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
2        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
3        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
4        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
3    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
4    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   

   Film-Noir  Western  
0        0.0      0.0  
1        0.0      0.0  
2        0.0      0.0  
3        0.0      0.0  
4        0.0      0.0

In [100]:
dummies.columns

Index(['Animation', 'Children's', 'Comedy', 'Adventure', 'Fantasy', 'Romance',
       'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi',
       'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir', 'Western'],
      dtype='object')

In [90]:
gen = base.genero #no funciona y no se que esta haciendo
gen

id
1        Animation|Children's|Comedy
2       Adventure|Children's|Fantasy
3                     Comedy|Romance
4                       Comedy|Drama
5                             Comedy
                    ...             
3948                          Comedy
3949                           Drama
3950                           Drama
3951                           Drama
3952                  Drama|Thriller
Name: genero, Length: 3883, dtype: object

In [107]:
y=gen.str.split("|")
y

id
1        [Animation, Children's, Comedy]
2       [Adventure, Children's, Fantasy]
3                      [Comedy, Romance]
4                        [Comedy, Drama]
5                               [Comedy]
                      ...               
3948                            [Comedy]
3949                             [Drama]
3950                             [Drama]
3951                             [Drama]
3952                   [Drama, Thriller]
Name: genero, Length: 3883, dtype: object

In [103]:
dummies.columns.get_indexer([y])

array([0, 1, 2], dtype=int64)

In [109]:
for i, gen in enumerate(base.genero):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [110]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    1.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       1.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [111]:
dummies.sum()

Animation       105.0
Children's      251.0
Comedy         1200.0
Adventure       283.0
Fantasy          68.0
Romance         471.0
Drama          1603.0
Action          503.0
Crime           211.0
Thriller        492.0
Horror          343.0
Sci-Fi          276.0
Documentary     127.0
War             143.0
Musical         114.0
Mystery         106.0
Film-Noir        44.0
Western          68.0
dtype: float64

In [112]:
movies_dummies = base.join(dummies.add_prefix('Genero_'))
movies_dummies.head()

genero  year                  Nom_pelicula  \
id                                                                     
1    Animation|Children's|Comedy  1995                    Toy Story    
2   Adventure|Children's|Fantasy  1995                      Jumanji    
3                 Comedy|Romance  1995             Grumpier Old Men    
4                   Comedy|Drama  1995            Waiting to Exhale    
5                         Comedy  1995  Father of the Bride Part II    

    Genero_Animation  Genero_Children's  Genero_Comedy  Genero_Adventure  \
id                                                                         
1                0.0                1.0            0.0               1.0   
2                0.0                0.0            1.0               0.0   
3                0.0                0.0            1.0               0.0   
4                0.0                0.0            1.0               0.0   
5                0.0                0.0            0.0               0.0   

    Genero_Fantasy  Genero_Romance  Genero_Drama  ...  Genero_Crime  \
id                                                ...                 
1              1.0             0.0           0.0  ...           0.0   
2              0.0             1.0           0.0  ...           0.0   
3              0.0             0.0           1.0  ...           0.0   
4              0.0             0.0           0.0  ...           0.0   
5              0.0             0.0           0.0  ...           1.0   

    Genero_Thriller  Genero_Horror  Genero_Sci-Fi  Genero_Documentary  \
id                                                                      
1               0.0            0.0            0.0                 0.0   
2               0.0            0.0            0.0                 0.0   
3               0.0            0.0            0.0                 0.0   
4               0.0            0.0            0.0                 0.0   
5               1.0            0.0            0.0                 0.0   

    Genero_War  Genero_Musical  Genero_Mystery  Genero_Film-Noir  \
id                                                                 
1          0.0             0.0             0.0               0.0   
2          0.0             0.0             0.0               0.0   
3          0.0             0.0             0.0               0.0   
4          0.0             0.0             0.0               0.0   
5          0.0             0.0             0.0               0.0   

    Genero_Western  
id                  
1              0.0  
2              0.0  
3              0.0  
4              0.0  
5              0.0  

[5 rows x 21 columns]

In [113]:
movies_dummies.iloc[1]

genero                Adventure|Children's|Fantasy
year                                          1995
Nom_pelicula                              Jumanji 
Genero_Animation                               0.0
Genero_Children's                              0.0
Genero_Comedy                                  1.0
Genero_Adventure                               0.0
Genero_Fantasy                                 0.0
Genero_Romance                                 1.0
Genero_Drama                                   0.0
Genero_Action                                  0.0
Genero_Crime                                   0.0
Genero_Thriller                                0.0
Genero_Horror                                  0.0
Genero_Sci-Fi                                  0.0
Genero_Documentary                             0.0
Genero_War                                     0.0
Genero_Musical                                 0.0
Genero_Mystery                                 0.0
Genero_Film-Noir               